//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintDashboard.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Complaint_DashboardEntities1 : DbContext
    {
        public Complaint_DashboardEntities1()
            : base("name=Complaint_DashboardEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Complaint> Complaints { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
    
        public virtual ObjectResult<Sel_IndivudualComplaint_Result> Sel_IndivudualComplaint(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sel_IndivudualComplaint_Result>("Sel_IndivudualComplaint", idParameter);
        }
    }
}
